version: '3'

services:
  harrison-portfolio:
    container_name: harrison-portfolio
    image: node:14
    restart: always
    working_dir: /app
    entrypoint: npm start
    volumes: 
      - ./:/app 
    ports:
      - 55055:3001
